data = [
    {'name': 'NASA', 'follower_count': 79, 'description': 'Space agency', 'country': 'United States'},
    {'name': 'SpaceX', 'follower_count': 21, 'description': 'Private space exploration company', 'country': 'United States'},
    {'name': 'Elon Musk', 'follower_count': 170, 'description': 'CEO of SpaceX and Tesla', 'country': 'United States'},
    {'name': 'European Space Agency', 'follower_count': 6, 'description': 'Intergovernmental space organisation', 'country': 'Europe'},
    {'name': 'Neil deGrasse Tyson', 'follower_count': 14, 'description': 'Astrophysicist and science communicator', 'country': 'United States'},
    {'name': 'Hubble Space Telescope', 'follower_count': 32, 'description': 'Space telescope launched in 1990', 'country': 'United States'},
    {'name': 'James Webb Space Telescope', 'follower_count': 47, 'description': 'Infrared space observatory', 'country': 'United States'},
    {'name': 'International Space Station', 'follower_count': 53, 'description': 'Modular space station in low Earth orbit', 'country': 'International'},
    {'name': 'Chris Hadfield', 'follower_count': 28, 'description': 'Canadian astronaut and author', 'country': 'Canada'},
    {'name': 'Blue Origin', 'follower_count': 19, 'description': 'Private aerospace manufacturer', 'country': 'United States'},
    {'name': 'Rocket Lab', 'follower_count': 67, 'description': 'Small satellite launch company', 'country': 'New Zealand'},
    {'name': 'Virgin Galactic', 'follower_count': 83, 'description': 'Commercial spaceflight company', 'country': 'United States'},
    {'name': 'ISRO', 'follower_count': 12, 'description': 'Indian Space Research Organisation', 'country': 'India'},
    {'name': 'JAXA', 'follower_count': 37, 'description': 'Japan Aerospace Exploration Agency', 'country': 'Japan'},
    {'name': 'Buzz Aldrin', 'follower_count': 91, 'description': 'Apollo 11 astronaut', 'country': 'United States'},
    {'name': 'Scott Kelly', 'follower_count': 44, 'description': 'NASA astronaut and author', 'country': 'United States'},
    {'name': 'Perseverance Rover', 'follower_count': 25, 'description': 'NASA Mars rover', 'country': 'United States'},
    {'name': 'Curiosity Rover', 'follower_count': 41, 'description': 'NASA Mars Science Laboratory rover', 'country': 'United States'},
    {'name': 'Brian Cox', 'follower_count': 38, 'description': 'Physicist and science broadcaster', 'country': 'United Kingdom'},
    {'name': 'Michio Kaku', 'follower_count': 22, 'description': 'Theoretical physicist and futurist', 'country': 'United States'},
    {'name': 'Artemis Program', 'follower_count': 16, 'description': 'NASA lunar exploration program', 'country': 'United States'},
    {'name': 'CNSA', 'follower_count': 7, 'description': 'China National Space Administration', 'country': 'China'},
    {'name': 'Roscosmos', 'follower_count': 5, 'description': 'Russian space agency', 'country': 'Russia'},
    {'name': 'Starlink', 'follower_count': 8, 'description': 'SpaceX satellite internet constellation', 'country': 'United States'},
    {'name': 'Carl Sagan', 'follower_count': 9, 'description': 'Astronomer and science communicator', 'country': 'United States'},
    {'name': 'ICEYE', 'follower_count': 15, 'description': 'SAR satellite operator', 'country': 'Finland'},
    {'name': 'Spire Global', 'follower_count': 18, 'description': 'Space-to-cloud data company', 'country': 'United States'},
    {'name': 'Planet Labs', 'follower_count': 23, 'description': 'Earth imaging satellite company', 'country': 'United States'},
    {'name': 'EUSPA', 'follower_count': 11, 'description': 'EU Agency for the Space Programme', 'country': 'Czech Republic'},
    {'name': 'Axiom Space', 'follower_count': 56, 'description': 'Commercial space station developer', 'country': 'United States'},
    {'name': 'Valentina Tereshkova', 'follower_count': 87, 'description': 'First woman in space', 'country': 'Russia'},
    {'name': 'Neil Armstrong', 'follower_count': 320, 'description': 'First human on the Moon', 'country': 'United States'},
    {'name': 'Yuri Gagarin', 'follower_count': 450, 'description': 'First human in space', 'country': 'Russia'},
    {'name': 'Mae Jemison', 'follower_count': 95, 'description': 'First African American woman in space', 'country': 'United States'},
    {'name': 'Sally Ride', 'follower_count': 210, 'description': 'First American woman in space', 'country': 'United States'},
    {'name': 'Andromeda Galaxy', 'follower_count': 180, 'description': 'Nearest spiral galaxy to the Milky Way', 'country': 'Universe'},
    {'name': 'Black Hole M87', 'follower_count': 430, 'description': 'First black hole ever photographed', 'country': 'Universe'},
    {'name': 'Voyager 1', 'follower_count': 520, 'description': 'Most distant human-made object', 'country': 'United States'},
    {'name': 'Apollo 11', 'follower_count': 980, 'description': 'First crewed Moon landing mission', 'country': 'United States'},
    {'name': 'Cassini-Huygens', 'follower_count': 340, 'description': 'Saturn orbiter and Titan probe', 'country': 'United States'},
    {'name': 'New Horizons', 'follower_count': 270, 'description': 'First spacecraft to visit Pluto', 'country': 'United States'},
    {'name': 'Stephen Hawking', 'follower_count': 3700, 'description': 'Theoretical physicist and cosmologist', 'country': 'United Kingdom'},
    {'name': 'Katherine Johnson', 'follower_count': 145, 'description': 'NASA mathematician and Hidden Figure', 'country': 'United States'},
    {'name': 'Wernher von Braun', 'follower_count': 230, 'description': 'Pioneer of rocket technology', 'country': 'United States'},
    {'name': 'Kalpana Chawla', 'follower_count': 560, 'description': 'First woman of Indian origin in space', 'country': 'United States'},
    {'name': 'Tim Peake', 'follower_count': 1200, 'description': 'British ESA astronaut', 'country': 'United Kingdom'},
    {'name': 'Thomas Pesquet', 'follower_count': 2300, 'description': 'French ESA astronaut', 'country': 'France'},
    {'name': 'Sunita Williams', 'follower_count': 890, 'description': 'NASA astronaut and record holder', 'country': 'United States'},
    {'name': 'Frank Rubio', 'follower_count': 385, 'description': 'NASA astronaut with record ISS stay', 'country': 'United States'},
    {'name': 'Sigmund Jahn', 'follower_count': 45, 'description': 'First German in space', 'country': 'Germany'},
    {'name': 'Samantha Cristoforetti', 'follower_count': 1800, 'description': 'Italian ESA astronaut and record holder', 'country': 'Italy'},
]
